backend:
  name: github
  repo: andidumitru96/s0-studi
  branch: main
  base_url: https://s0-studio-oauth.andi-dumitru.workers.dev
  auth_endpoint: /auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Featured (Homepage)", name: "featured", widget: "boolean", required: false }
      - { label: "Images", name: "images", widget: "image", multiple: true }
      - { label: "Description", name: "body", widget: "markdown" }
